version: '3.3'

services:
  doctor:
    build: doctorservice
    container_name: doctorService
    image: book_my_consultation/doctorservice:1.0.0
    ports:
     - "8081:8081"
    environment:
     - MONGO_HOST
     - KAFKA_HOST
     - INSTANCE_IP
    depends_on:
      - notification
    networks:
      - app-tier
  user:
    build: userservice
    container_name: userService
    image: book_my_consultation/userservice:1.0.0
    ports:
     - "8082:8082"
    environment:
     - MONGO_HOST
     - KAFKA_HOST
     - INSTANCE_IP
    networks:
      - app-tier
  appointment:
    build: appointmentservice
    container_name: appointmentService
    image: book_my_consultation/appointmentservice:1.0.0
    ports:
     - "8083:8083"
    environment:
     - MYSQL_HOST
     - MONGO_HOST
     - KAFKA_HOST
     - INSTANCE_IP
    depends_on:
      - notification
      - doctor
      - user
    networks:
      - app-tier
  payment:
    build: paymentservice
    container_name: paymentService
    image: book_my_consultation/paymentservice:1.0.0
    ports:
     - "8084:8084"
    environment:
     - KAFKA_HOST
     - INSTANCE_IP
    depends_on:
      - appointment
      - notification
    networks:
      - app-tier
  rating:
    build: ratingservice
    container_name: ratingService
    image: book_my_consultation/ratingservice:1.0.0
    ports:
     - "8085:8085"
    environment:
     - MONGO_HOST
     - KAFKA_HOST
     - INSTANCE_IP
    depends_on:
      - doctor
    networks:
      - app-tier
  notification:
    build: notificationservice
    container_name: notificationService
    image: book_my_consultation/notificationservice:1.0.0
    environment:
     - KAFKA_HOST
     - INSTANCE_IP
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge